# Manage an ADS-backed bibliography for a LaTeX document.
#
# This file contains two packages. ManagedBibliography reads the .aux file,
# finds unresolved citation keys, fetches matching entries from ADS, and
# updates the managed .bib file.
#
# The main package at the end connects that logic to latexmk. It reads
# settings from latexmkrc, maps $Pbase to document_base, and installs hooks
# when add_hook is available.
#
# Project home:
#   https://github.com/svaberg/managed-bibliography
#

package ManagedBibliography;

use strict;
use warnings;

use File::Temp qw(tempfile);
use HTTP::Tiny;
use JSON::PP qw(decode_json encode_json);

use constant DEFAULT_BIB_FILE_EXTENSION => 'adskeys.bib';
use constant DEFAULT_ADS_QUERY_CHUNK_SIZE => 25;

use constant ADS_STATUS_OK => 'ok';
use constant ADS_STATUS_AUTH => 'auth';
use constant ADS_STATUS_ERROR => 'error';

use constant ADS_HTTP_UNAUTHORIZED => 401;
use constant ADS_HTTP_FORBIDDEN => 403;

use constant ADS_SEARCH_QUERY_URL => 'https://api.adsabs.harvard.edu/v1/search/query';
use constant ADS_EXPORT_BIBTEX_URL => 'https://api.adsabs.harvard.edu/v1/export/bibtex';

use constant ADS_TOKEN_ENV_VARS => ('ADS_API_TOKEN', 'ADS_DEV_KEY');
use constant ADS_TOKEN_FILE_BASENAMES => ('token', 'dev_key');

use constant MANAGED_BIBLIOGRAPHY_HEADER => <<'EOF';
% Managed bibliography file generated by managed-bibliography.pl.
% This file is maintained automatically from ADS lookups.
% Manual edits may be overwritten.
EOF


# Read the LaTeX build state, resolve missing ADS entries, and update the
# managed bibliography file.
sub manage_bibliography {
    my (%args) = @_;

    my $document_base = $args{document_base};
    die "manbib: document_base is required.\n"
      if !defined $document_base || $document_base eq '';
    my $managed_bib_file = $args{managed_bib_file};
    my $ads_api_token = $args{ads_api_token};
    my $bib_file_extension = $args{bib_file_extension} // DEFAULT_BIB_FILE_EXTENSION;

    print "manbib: ******************************************************\n";
    print "manbib: * Forget bibliography management with pure ADS keys! *\n";
    print "manbib: ******************************************************\n";

    my $aux_file = "$document_base.aux";
    if (!defined $managed_bib_file) {
        $managed_bib_file = "$document_base.$bib_file_extension";
    }

    if (!-e $managed_bib_file) {
        print "manbib: Creating managed bibliography file $managed_bib_file (first use).\n";
        write_managed_bibliography_file($managed_bib_file, {});
    }

    my @bibtex_files = discover_bibtex_files($aux_file);
    if (not @bibtex_files) {
        print "manbib: No bibliography files found in $aux_file; nothing to do.\n";
        return 0;
    }
    if (!grep { $_ eq $managed_bib_file } @bibtex_files) {
        my $managed_bibdata = $managed_bib_file;
        $managed_bibdata =~ s/\.bib\z//i;
        my @bibdata = @bibtex_files;
        s/\.bib\z//i for @bibdata;
        my $current_command = '\\bibliography{' . join(',', @bibdata) . '}';
        print "manbib: Managed bibliography file $managed_bib_file is not listed in the document's \\bibliography{...} command.\n";
        print "manbib: Current bibliography setup appears to be $current_command.\n";
        print "manbib: Add $managed_bibdata to that command, or set \$managed_bib_file to match it; nothing to do.\n";
        return 0;
    }

    my %keys = parse_keys($aux_file);

    my @user_bibtex_files = grep { $_ ne $managed_bib_file && -e $_ } @bibtex_files;
    my %available_keys = read_bibliography_keys($managed_bib_file, @user_bibtex_files);
    my @missing_keys = sort grep { !$available_keys{$_} } keys %keys;

    if (!@missing_keys) {
        print "manbib: All citation keys are already satisfied by local bibliography files.\n";
        return 0;
    }

    print "manbib: Need ADS entries for ", scalar(@missing_keys), " citation keys.\n";
    if (!defined $ads_api_token || $ads_api_token eq '') {
        print "manbib: ADS API token unavailable (looked for ADS_API_TOKEN, ADS_DEV_KEY, ~/.ads/token, ~/.ads/dev_key, and \$ads_api_token); leaving missing keys unresolved.\n";
        return 0;
    }

    my ($status, $content, $detail) = fetch_missing_ads_entries(
        \@missing_keys,
        $ads_api_token,
    );

    if ($status eq ADS_STATUS_AUTH) {
        report_ads_auth_failure($detail);
        return 0;
    }

    if ($status eq ADS_STATUS_OK) {
        my %fetched_keys = %{$detail};
        for my $key (@missing_keys) {
            if ($fetched_keys{$key}) {
                print "manbib: ADS returned entry for <$key>.\n";
            }
            else {
                print "manbib: ADS returned no entry for <$key>; leaving it unresolved.\n";
            }
        }

        if (defined $content && length $content) {
            append_bibliography_entries($managed_bib_file, $content);
        }
    }
    else {
        for my $key (@missing_keys) {
            print "manbib: ADS lookup failed for <$key>; leaving it unresolved.\n";
        }
    }

    return 0;
}


# Read the bibliography file list recorded in the .aux file.
sub discover_bibtex_files {
    my ($aux_file) = @_;

    my @bibtex_files;

    open my $fh, '<', $aux_file or die "manbib: Cannot open $aux_file: $!";
    binmode($fh, ':encoding(UTF-8)');
    while (<$fh>) {
        if (/^\\bibdata\{([^}]*)\}/) {
            @bibtex_files
             = map { /\.bib$/i ? $_ : "$_.bib" } grep /\S/, split /,/, $1;
            last;
        }
    }
    close $fh;

    return @bibtex_files;
}


# Read cited keys from the .aux file.
sub parse_keys {
    my ($aux_file) = @_;
    print "manbib: Reading citation keys from $aux_file...\n";

    my %keys;
    open my $fh, '<', $aux_file or die "manbib: Cannot open $aux_file: $!";
    binmode($fh, ':encoding(UTF-8)');
    while (my $line = <$fh>) {
        if ($line =~ /^\\citation\{([^}]*)\}/) {
            $keys{$_} = 1 for grep { $_ ne '' } split /,/, $1;
        }
        if ($line =~ /^\\abx\@aux\@cite\{[^}]*\}\{([^}]*)\}/) {
            $keys{$1} = 1;
        }
    }
    close $fh;
    print "manbib: Finished reading ", scalar(keys %keys), " citation keys from $aux_file.\n";

    return %keys;
}


# Read entry keys already present in the managed and user bibliography files.
sub read_bibliography_keys {
    my @files = @_;
    my %keys;

    for my $file (@files) {
        next if !defined $file || !-e $file;
        print "manbib: Reading bibliography keys from $file...\n";
        open my $fh, '<', $file or die "manbib: Cannot open $file: $!";
        binmode($fh, ':encoding(UTF-8)');
        local $/ = undef;
        my $content = <$fh>;
        close $fh;

        my %file_keys = extract_bibliography_keys_from_text($content);
        $keys{$_} = 1 for keys %file_keys;
    }

    return %keys;
}


# Print a single clear authentication failure message for ADS token problems.
sub report_ads_auth_failure {
    my ($detail) = @_;
    my $http_status = defined $detail ? $detail : 'unknown';
    print "manbib: ADS authentication failed (HTTP $http_status). Check ADS_API_TOKEN, ADS_DEV_KEY, ~/.ads/token, ~/.ads/dev_key, or \$ads_api_token; leaving missing keys unresolved.\n";
}


# Resolve missing keys via ADS, export matching BibTeX entries, and rewrite
# exported entry ids back to the keys cited in the document.
sub fetch_missing_ads_entries {
    my ($missing_keys_ref, $ads_api_token) = @_;

    my ($resolve_status, $resolved_keys, $resolve_detail) = resolve_ads_bibcodes(
        $missing_keys_ref,
        ads_api_token => $ads_api_token,
    );
    return ($resolve_status, undef, $resolve_detail) if $resolve_status ne ADS_STATUS_OK;

    my %canonical_for = %{$resolved_keys};
    my %requested_keys_for;
    for my $key (sort keys %canonical_for) {
        my $canonical = $canonical_for{$key};
        push @{$requested_keys_for{$canonical}}, $key;
        if ($canonical ne $key) {
            print "manbib: ADS canonicalized <$key> => <$canonical>.\n";
        }
    }

    my @canonical_keys = sort keys %requested_keys_for;
    return (ADS_STATUS_OK, '', {}) if !@canonical_keys;

    my ($fetch_status, $fetch_content, $fetch_detail) = fetch_ads_bibtex_entries(
        \@canonical_keys,
        ads_api_token => $ads_api_token,
    );
    return ($fetch_status, undef, $fetch_detail) if $fetch_status ne ADS_STATUS_OK;

    my ($rewritten_content, $fetched_requested_keys) =
      remap_exported_entries_to_requested_keys($fetch_content, \%requested_keys_for);
    return (ADS_STATUS_OK, $rewritten_content, $fetched_requested_keys);
}


# Build a default ADS HTTP client with the configured bearer token.
sub ads_http_client {
    my ($ads_api_token) = @_;
    return HTTP::Tiny->new(
        default_headers => {
            Authorization => 'Bearer ' . ($ads_api_token // ''),
        },
    );
}


# Percent-encode a string for use in ADS URLs.
sub uri_escape {
    my ($text) = @_;
    $text =~ s/([^A-Za-z0-9\-\._~])/sprintf("%%%02X", ord($1))/ge;
    return $text;
}


# Encode a small query parameter hash for an ADS GET request.
sub url_encode_form {
    my (%params) = @_;
    return join('&', map { uri_escape($_) . '=' . uri_escape($params{$_}) } sort keys %params);
}


# Escape backslashes and double quotes inside an ADS identifier query phrase.
sub escape_ads_query_phrase {
    my ($text) = @_;
    $text =~ s/\\/\\\\/g;
    $text =~ s/"/\\"/g;
    return $text;
}


# Decode ADS JSON payloads and report malformed responses consistently.
sub decode_ads_json_content {
    my ($content, $context) = @_;

    my $body;
    eval { $body = decode_json($content); 1 }
      or do {
          warn "manbib: ADS $context returned invalid JSON.\n";
          return undef;
      };

    return $body;
}


# Ask ADS which canonical bibcodes correspond to the cited identifiers.
sub resolve_ads_bibcodes {
    my ($keys_ref, %args) = @_;

    my $ads_api_token = $args{ads_api_token};
    my $http = $args{http_client};
    if (!defined $http) {
        $http = ads_http_client($ads_api_token);
    }

    my @keys = @{$keys_ref};
    my %canonical_for;
    my $chunk_size = $args{chunk_size} // DEFAULT_ADS_QUERY_CHUNK_SIZE;

    while (@keys) {
        my @chunk = splice(@keys, 0, $chunk_size);
        my $query = join(' OR ', map { 'identifier:"' . escape_ads_query_phrase($_) . '"' } @chunk);
        my $url = ADS_SEARCH_QUERY_URL . '?'
          . url_encode_form(
              fl => 'bibcode,identifier',
              q => $query,
              rows => scalar(@chunk),
          );

        my $response = $http->get($url);
        if ($response->{success}) {
            my $body = decode_ads_json_content($response->{content}, 'identifier search');
            return (ADS_STATUS_ERROR, undef, undef) if !defined $body;

            my $docs = $body->{response}{docs};
            if (ref($docs) ne 'ARRAY') {
                warn "manbib: ADS identifier search returned an unexpected payload.\n";
                return (ADS_STATUS_ERROR, undef, undef);
            }

            for my $doc (@{$docs}) {
                my $bibcode = $doc->{bibcode};
                next if !defined $bibcode || $bibcode eq '';

                my @identifiers;
                if (ref($doc->{identifier}) eq 'ARRAY') {
                    @identifiers = @{$doc->{identifier}};
                }
                elsif (defined $doc->{identifier}) {
                    @identifiers = ($doc->{identifier});
                }
                push @identifiers, $bibcode;

                my %identifier_lookup = map { $_ => 1 } @identifiers;
                for my $key (@chunk) {
                    if ($identifier_lookup{$key}) {
                        $canonical_for{$key} = $bibcode;
                    }
                }
            }
            next;
        }
        if (($response->{status} // 0) == ADS_HTTP_UNAUTHORIZED
            || ($response->{status} // 0) == ADS_HTTP_FORBIDDEN) {
            return (ADS_STATUS_AUTH, undef, $response->{status});
        }

        warn "manbib: ADS identifier search failed with status ", ($response->{status} // 'unknown'), ".\n";
        return (ADS_STATUS_ERROR, undef, undef);
    }

    return (ADS_STATUS_OK, \%canonical_for, undef);
}


# Bulk-export BibTeX entries from ADS for canonical bibcodes.
sub fetch_ads_bibtex_entries {
    my ($keys_ref, %args) = @_;

    my $ads_api_token = $args{ads_api_token};
    my $http = $args{http_client};
    if (!defined $http) {
        $http = ads_http_client($ads_api_token);
    }

    my $url = ADS_EXPORT_BIBTEX_URL;
    my $response = $http->post(
        $url,
        {
            headers => {
                Authorization => 'Bearer ' . ($ads_api_token // ''),
                'Content-Type' => 'application/json',
            },
            content => encode_json({ bibcode => $keys_ref }),
        },
    );

    if ($response->{success}) {
        my $body = decode_ads_json_content($response->{content}, 'bulk export');
        return (ADS_STATUS_ERROR, undef, undef) if !defined $body;

        my $export = $body->{export} // '';
        return (ADS_STATUS_OK, $export, undef);
    }
    if (($response->{status} // 0) == 404) {
        return (ADS_STATUS_OK, '', undef);
    }
    if (($response->{status} // 0) == ADS_HTTP_UNAUTHORIZED
        || ($response->{status} // 0) == ADS_HTTP_FORBIDDEN) {
        return (ADS_STATUS_AUTH, undef, $response->{status});
    }

    warn "manbib: ADS bulk export failed with status ", ($response->{status} // 'unknown'), ".\n";
    return (ADS_STATUS_ERROR, undef);
}


# Replace the key on a single BibTeX entry without touching its body.
sub replace_bibliography_entry_key {
    my ($entry, $new_key) = @_;
    $entry =~ s/^([ \t]*\@[A-Za-z]+\s*[\{\(]\s*)[^,\s]+/$1$new_key/m
      or die "manbib: Could not rewrite bibliography entry key to $new_key.";
    return $entry;
}


# Rewrite exported canonical entries back to the keys actually cited in the
# document.
sub remap_exported_entries_to_requested_keys {
    my ($content, $requested_keys_for_ref) = @_;

    my %entries = extract_bibliography_entries_from_text($content // '');
    my @rewritten_entries;
    my %fetched_requested_keys;

    for my $canonical_key (sort keys %{$requested_keys_for_ref}) {
        next if !exists $entries{$canonical_key};
        for my $requested_key (sort @{$requested_keys_for_ref->{$canonical_key}}) {
            push @rewritten_entries, replace_bibliography_entry_key($entries{$canonical_key}, $requested_key);
            $fetched_requested_keys{$requested_key} = 1;
        }
    }

    return (join("\n\n", @rewritten_entries), \%fetched_requested_keys);
}


# Merge new ADS entries into the managed bibliography and rewrite the file in a
# stable sorted order.
sub append_bibliography_entries {
    my ($managed_bib_file, @entries) = @_;
    return if !@entries;

    my %managed_entries;
    if (-e $managed_bib_file) {
        open my $fh, '<', $managed_bib_file or die "manbib: Cannot open $managed_bib_file: $!";
        binmode($fh, ':encoding(UTF-8)');
        local $/ = undef;
        my $existing = <$fh> // '';
        close $fh;
        %managed_entries = extract_bibliography_entries_from_text($existing);
    }

    for my $entry (@entries) {
        my %new_entries = extract_bibliography_entries_from_text($entry);
        $managed_entries{$_} = $new_entries{$_} for keys %new_entries;
    }

    my $entry_count = scalar(keys %managed_entries);
    my $entry_label = $entry_count == 1 ? 'entry' : 'entries';

    print "manbib: Writing $entry_count ADS $entry_label to $managed_bib_file...\n";

    write_managed_bibliography_file($managed_bib_file, \%managed_entries);
}


# Write the managed bibliography file atomically with the standard header and
# sorted entries.
sub write_managed_bibliography_file {
    my ($managed_bib_file, $entries_ref) = @_;

    my ($fh, $tmp_file) = open_temp_output($managed_bib_file);
    print {$fh} managed_bibliography_header();

    my @sorted_keys = sort keys %{$entries_ref};
    if (@sorted_keys) {
        print {$fh} "\n";
    }
    for my $index (0 .. $#sorted_keys) {
        my $entry = $entries_ref->{$sorted_keys[$index]};
        $entry =~ s/\s+\z//;
        print {$fh} $entry;
        print {$fh} "\n";
        print {$fh} "\n" if $index < $#sorted_keys;
    }

    close $fh or die "close $tmp_file: $!";
    rename $tmp_file, $managed_bib_file or die "rename $tmp_file -> $managed_bib_file: $!";
}


# Return the fixed header placed at the top of the managed bibliography file.
sub managed_bibliography_header {
    return MANAGED_BIBLIOGRAPHY_HEADER;
}


# Parse full BibTeX entries from text while respecting nested braces and
# quoted strings.
sub extract_bibliography_entries_from_text {
    my ($content) = @_;
    my %entries;

    pos($content) = 0;
    while ($content =~ /^[ \t]*\@([A-Za-z]+)\s*([\{\(])\s*([^,\s]+)\s*,/mg) {
        my ($type, $open, $key) = ($1, $2, $3);
        my $start = $-[0];
        my $close = $open eq '{' ? '}' : ')';
        my $track_quotes = $open eq '(';
        my $depth = 1;
        my $cursor = pos($content);
        my $in_quotes = 0;
        my $escape = 0;

        while ($cursor < length($content) && $depth > 0) {
            my $char = substr($content, $cursor, 1);
            if ($track_quotes && $in_quotes) {
                if ($escape) {
                    $escape = 0;
                }
                elsif ($char eq '\\') {
                    $escape = 1;
                }
                elsif ($char eq '"') {
                    $in_quotes = 0;
                }
            }
            else {
                if ($track_quotes && $char eq '"') {
                    $in_quotes = 1;
                }
                elsif ($char eq $open) {
                    $depth++;
                }
                elsif ($char eq $close) {
                    $depth--;
                }
            }
            $cursor++;
        }

        my $entry = substr($content, $start, $cursor - $start);
        if ($type !~ /^(comment|string|preamble)$/i && length $key) {
            $entries{$key} = $entry;
        }
        pos($content) = $cursor;
    }

    return %entries;
}


# Parse only entry keys from BibTeX text.
sub extract_bibliography_keys_from_text {
    my ($content) = @_;
    my %keys;

    while ($content =~ /^[ \t]*\@([A-Za-z]+)\s*[\{\(]\s*([^,\s]+)\s*,/mg) {
        my ($type, $key) = ($1, $2);
        next if $type =~ /^(comment|string|preamble)$/i;
        $keys{$key} = 1 if length $key;
    }

    return %keys;
}


# Open a temporary output file next to the target bibliography file.
sub open_temp_output {
    my ($target_file) = @_;

    my $dir = '.';
    my $basename = $target_file;
    if ($target_file =~ m{^(.*)/([^/]+)$}) {
        $dir = $1;
        $basename = $2;
    }

    my ($fh, $tmp_file) = tempfile("$basename.XXXXXX", DIR => $dir, UNLINK => 0);
    binmode($fh, ':encoding(UTF-8)');
    return ($fh, $tmp_file);
}


# Remove the generated managed bibliography file during a full clean.
sub delete_managed_bibliography {
    my (%args) = @_;

    my $managed_bib_file = $args{managed_bib_file};
    return 0 if !defined $managed_bib_file;

    if (-e $managed_bib_file) {
        print "manbib: Removing generated file $managed_bib_file during clean.\n";
        unlink $managed_bib_file or warn "manbib: Could not remove $managed_bib_file: $!";
    }
    return 0;
}


package main;

use strict;
use warnings;
use File::Spec;

our $Pbase;


# Discover the ADS token from environment variables, token files, or the
# latexmkrc setting.
sub discover_ads_api_token {
    no warnings 'once';

    for my $env_var (ManagedBibliography::ADS_TOKEN_ENV_VARS()) {
        my $token = $ENV{$env_var};
        return $token if defined $token && $token ne '';
    }

    for my $file (ads_api_token_files()) {
        next if !-r $file;
        open my $fh, '<', $file or next;
        my $token = <$fh>;
        close $fh;
        next if !defined $token;
        $token =~ s/\s+\z//;
        return $token if $token ne '';
    }

    my $token = $main::ads_api_token;
    return $token if defined $token && $token ne '';
    return undef;
}


# Return the standard per-user ADS token file locations.
sub ads_api_token_files {
    my @homes;

    push @homes, $ENV{HOME}
      if defined $ENV{HOME} && $ENV{HOME} ne '';
    push @homes, $ENV{USERPROFILE}
      if defined $ENV{USERPROFILE}
      && $ENV{USERPROFILE} ne ''
      && !grep { $_ eq $ENV{USERPROFILE} } @homes;
    push @homes, File::Spec->catdir($ENV{HOMEDRIVE}, $ENV{HOMEPATH})
      if !@homes
      && defined $ENV{HOMEDRIVE}
      && defined $ENV{HOMEPATH}
      && $ENV{HOMEDRIVE} ne ''
      && $ENV{HOMEPATH} ne '';

    my @files;
    for my $home (@homes) {
        push @files, map { File::Spec->catfile($home, '.ads', $_) }
          ManagedBibliography::ADS_TOKEN_FILE_BASENAMES();
    }

    return @files;
}


# Gather the current latexmk-facing settings into one hash.
sub current_settings {
    no warnings 'once';
    return (
        managed_bib_file => $main::managed_bib_file // undef,
        ads_api_token => discover_ads_api_token(),
        delete_on_full_clean => $main::delete_on_full_clean // 0,
        bib_file_extension => $main::bib_file_extension // ManagedBibliography::DEFAULT_BIB_FILE_EXTENSION,
    );
}


# Adapt latexmk's $Pbase into the stricter ManagedBibliography interface.
sub manage_bibliography {
    my %settings = current_settings();
    return ManagedBibliography::manage_bibliography(
        document_base => $$Pbase,
        managed_bib_file => $settings{managed_bib_file},
        ads_api_token => $settings{ads_api_token},
        bib_file_extension => $settings{bib_file_extension},
    );
}


# Adapt latexmk settings into a cleanup call for the managed bibliography file.
sub delete_managed_bibliography {
    my %settings = current_settings();
    my $managed_bib_file = $settings{managed_bib_file};
    if (!defined $managed_bib_file) {
        $managed_bib_file = "$$Pbase.$settings{bib_file_extension}";
    }
    return ManagedBibliography::delete_managed_bibliography(
        managed_bib_file => $managed_bib_file,
    );
}


# Register the bibliography-management hooks with latexmk when available.
sub install_latexmk_hooks {
    my %settings = current_settings();
    add_hook('before_xlatex', 'manage_bibliography');
    if ($settings{delete_on_full_clean}) {
        add_hook('cleanup_extra_full', 'delete_managed_bibliography');
    }
    return 0;
}


install_latexmk_hooks() if defined &add_hook;

1;
