use strict;
use warnings;

use Cwd qw(getcwd);
use File::Copy qw(copy);
use File::Spec;
use File::Temp qw(tempdir);
use FindBin qw($Bin);
use IPC::Cmd qw(can_run);
use Test::More;

my @required_commands = qw(latexmk pdflatex bibtex);
my @missing_commands = grep { !can_run($_) } @required_commands;

plan skip_all => 'requires latexmk, pdflatex, and bibtex'
  if @missing_commands;


sub write_file {
    my ($path, $content) = @_;
    open my $fh, '>', $path or die "open $path: $!";
    print {$fh} $content;
    close $fh or die "close $path: $!";
}


sub read_file {
    my ($path) = @_;
    open my $fh, '<', $path or die "open $path: $!";
    local $/ = undef;
    my $content = <$fh>;
    close $fh or die "close $path: $!";
    return $content;
}


sub copy_repo_file {
    my ($name, $tmpdir) = @_;
    my $source = File::Spec->catfile($Bin, '..', $name);
    my $target = File::Spec->catfile($tmpdir, $name);
    copy($source, $target) or die "copy $source -> $target: $!";
}


sub shell_quote {
    my ($text) = @_;
    $text =~ s/'/'\\''/g;
    return "'$text'";
}


sub write_latexmk_project {
    my ($tmpdir) = @_;

    copy_repo_file('managed-bibliography.pl', $tmpdir);
    copy_repo_file('latexmkrc', $tmpdir);

    write_file(
        File::Spec->catfile($tmpdir, 'paper.tex'),
        <<'EOF'
\documentclass{article}
\begin{document}
Hello \cite{localkey}.
\bibliographystyle{plain}
\bibliography{paper.adskeys,custom}
\end{document}
EOF
    );

    write_file(
        File::Spec->catfile($tmpdir, 'custom.bib'),
        <<'EOF'
@article{localkey,
  author = {Doe, Jane},
  title = {Local Entry},
  journal = {Journal of Testing},
  year = {2024},
}
EOF
    );
}


sub run_command_in_dir {
    my ($tmpdir, @cmd) = @_;

    my $cwd = getcwd();
    my $log_file = File::Spec->catfile($tmpdir, 'command.log');
    my $status;

    my $ok = eval {
        chdir $tmpdir or die "chdir $tmpdir: $!";
        local $ENV{HOME} = $tmpdir;
        local $ENV{ADS_API_TOKEN} = '';
        local $ENV{ADS_DEV_KEY} = '';
        local $ENV{USERPROFILE};
        local $ENV{HOMEDRIVE};
        local $ENV{HOMEPATH};
        my $command = join ' ', map { shell_quote($_) } @cmd;
        $command .= ' > ' . shell_quote($log_file) . ' 2>&1';
        system('/bin/sh', '-c', $command);
        $status = $? == -1 ? -1 : $? >> 8;
        1;
    };
    my $error = $@;
    chdir $cwd or die "chdir $cwd: $!";

    my $output = read_file($log_file);
    unlink $log_file or die "unlink $log_file: $!";
    die $error if !$ok;

    return ($status, $output);
}


subtest 'latexmk builds a document that uses only local bibliography entries' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);
    write_latexmk_project($tmpdir);

    my ($status, $output) = run_command_in_dir(
        $tmpdir,
        'latexmk',
        '-norc',
        '-r',
        'latexmkrc',
        '-pdf',
        '-bibtex',
        'paper.tex',
    );

    is($status, 0, 'latexmk build succeeds');
    ok(-e File::Spec->catfile($tmpdir, 'paper.pdf'), 'pdf is produced');
    ok(-e File::Spec->catfile($tmpdir, 'paper.adskeys.bib'), 'managed bibliography file is created');
    like(
        read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib')),
        qr/^% Managed bibliography file generated by managed-bibliography\.pl\./m,
        'managed bibliography file has its generated header',
    );
    like(
        read_file(File::Spec->catfile($tmpdir, 'paper.bbl')),
        qr/\\bibitem\{localkey\}/,
        'local bibliography entry is present in the generated bbl',
    );
    unlike($output, qr/^! /m, 'latexmk run does not hit a TeX error');
};


subtest 'latexmk full clean removes the managed bibliography file and sidecar map' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);
    write_latexmk_project($tmpdir);

    my ($build_status) = run_command_in_dir(
        $tmpdir,
        'latexmk',
        '-norc',
        '-r',
        'latexmkrc',
        '-pdf',
        '-bibtex',
        'paper.tex',
    );
    is($build_status, 0, 'setup build succeeds before cleanup');

    write_file(
        File::Spec->catfile($tmpdir, 'paper.adskeys.map'),
        <<'EOF'
# Managed ADS canonical key map generated by managed-bibliography.pl.
# cited_key<TAB>canonical_ads_key_or_-
EOF
    );

    ok(-e File::Spec->catfile($tmpdir, 'paper.adskeys.bib'), 'managed bibliography file exists before clean');
    ok(-e File::Spec->catfile($tmpdir, 'paper.adskeys.map'), 'managed sidecar map exists before clean');

    my ($clean_status, $clean_output) = run_command_in_dir(
        $tmpdir,
        'latexmk',
        '-norc',
        '-r',
        'latexmkrc',
        '-C',
        'paper.tex',
    );

    is($clean_status, 0, 'latexmk full clean succeeds');
    ok(!-e File::Spec->catfile($tmpdir, 'paper.adskeys.bib'), 'managed bibliography file is removed by full clean');
    ok(!-e File::Spec->catfile($tmpdir, 'paper.adskeys.map'), 'managed sidecar map is removed by full clean');
    ok(-e File::Spec->catfile($tmpdir, 'paper.tex'), 'source tex file is kept');
    ok(-e File::Spec->catfile($tmpdir, 'custom.bib'), 'user bibliography file is kept');
    like($clean_output, qr/Removing generated file paper\.adskeys\.bib during clean\./, 'clean log reports managed bibliography removal');
    like($clean_output, qr/Removing generated file paper\.adskeys\.map during clean\./, 'clean log reports sidecar removal');
};


done_testing;
