use strict;
use warnings;

use Cwd qw(getcwd);
use FindBin qw($Bin);
use File::Spec;
use File::Temp qw(tempdir);
use Test::More;

my $script = File::Spec->catfile($Bin, '..', 'managed-bibliography.pl');
my $rv = do $script;
die $@ if $@;
die "could not load $script: $!" if !defined $rv;


sub write_file {
    my ($path, $content) = @_;
    open my $fh, '>', $path or die "open $path: $!";
    print {$fh} $content;
    close $fh or die "close $path: $!";
}


sub read_file {
    my ($path) = @_;
    open my $fh, '<', $path or die "open $path: $!";
    local $/ = undef;
    my $content = <$fh>;
    close $fh or die "close $path: $!";
    return $content;
}


sub managed_bib_with_header {
    my ($entries) = @_;
    my $header = <<'EOF';
% Managed bibliography file generated by managed-bibliography.pl.
% This file is maintained automatically from ADS lookups.
% Manual edits may be overwritten.
EOF

    return $header if !defined $entries || $entries eq '';
    return $header . "\n" . $entries;
}


sub capture_stdout {
    my ($code) = @_;
    my $output = '';
    open my $fh, '>', \$output or die "open scalar stdout: $!";
    local *STDOUT = $fh;
    my $result = $code->();
    return ($result, $output);
}


sub run_in_dir {
    my ($dir, $code) = @_;
    my $cwd = getcwd();
    chdir $dir or die "chdir $dir: $!";
    my @result = eval { $code->() };
    my $error = $@;
    chdir $cwd or die "chdir $cwd: $!";
    die $error if $error;
    return @result;
}


{
    package LocalHTTPClient;

    sub new {
        my ($class, %args) = @_;
        return bless \%args, $class;
    }

    sub get {
        my ($self, $url) = @_;
        push @{$self->{seen_urls}}, $url;
        return $self->{get_response};
    }
}


subtest 'ADS token discovery follows adstex-style lookup order' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);
    my $adsdir = File::Spec->catdir($tmpdir, '.ads');
    mkdir $adsdir or die "mkdir $adsdir: $!";

    write_file(File::Spec->catfile($adsdir, 'token'), "file-token\n");
    write_file(File::Spec->catfile($adsdir, 'dev_key'), "file-dev-token\n");

    local $ENV{HOME} = $tmpdir;
    local $ENV{USERPROFILE};
    local $ENV{HOMEDRIVE};
    local $ENV{HOMEPATH};
    local $ENV{ADS_API_TOKEN};
    local $ENV{ADS_DEV_KEY};
    no warnings 'once';
    local $main::ads_api_token = 'rc-token';

    is(main::discover_ads_api_token(), 'file-token', 'file token is used before the latexmkrc setting');

    local $ENV{ADS_DEV_KEY} = 'env-dev-token';
    is(main::discover_ads_api_token(), 'env-dev-token', 'ADS_DEV_KEY is used before token files');

    local $ENV{ADS_API_TOKEN} = 'env-api-token';
    is(main::discover_ads_api_token(), 'env-api-token', 'ADS_API_TOKEN has highest priority');
};


subtest 'ADS identifier search canonicalizes alternate keys' => sub {
    my $http = LocalHTTPClient->new(
        get_response => {
            success => 1,
            content => <<'EOF',
{"response":{"docs":[
  {"bibcode":"2009LanB...4B..712L","identifier":["2009LanB...4B...44L","2009LanB...4B..712L"]},
  {"bibcode":"2020NaMet..17..261V","identifier":["2020NatMe..17..261V","2020NaMet..17..261V"]}
]}}
EOF
        },
        seen_urls => [],
    );

    my ($status, $resolved, $detail) = ManagedBibliography::resolve_ads_bibcodes(
        [qw(2009LanB...4B...44L 2020NatMe..17..261V)],
        ads_api_token => 'token',
        http_client => $http,
    );

    is($status, 'ok', 'identifier resolution succeeds');
    is($detail, undef, 'no extra detail is returned on success');
    is_deeply(
        $resolved,
        {
            '2009LanB...4B...44L' => '2009LanB...4B..712L',
            '2020NatMe..17..261V' => '2020NaMet..17..261V',
        },
        'alternate identifiers are mapped to canonical bibcodes',
    );
    like(
        $http->{seen_urls}[0],
        qr/identifier%3A%222009LanB\.\.\.4B\.\.\.44L%22/,
        'identifier search is sent to ADS',
    );
};


subtest 'local bibliography plus missing ADS key without token' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{paper.adskeys,custom}
\citation{localkey,missingkey}
EOF
    );

    write_file(
        File::Spec->catfile($tmpdir, 'custom.bib'),
        <<'EOF'
@article{localkey,
  title = {Local},
}
EOF
    );

    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success without token');
    like($stdout, qr/ADS API token unavailable/, 'missing token is reported');
    is(
        read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib')),
        managed_bib_with_header(''),
        'managed bibliography keeps only its header when nothing can be fetched',
    );
    ok(!-e File::Spec->catfile($tmpdir, 'paper.keys.tex'), 'no citation key cache file is created');
};


subtest 'managed bibliography not listed in \\bibliography command is reported clearly' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{adstex,custom}
\citation{missingkey}
EOF
    );

    write_file(
        File::Spec->catfile($tmpdir, 'custom.bib'),
        <<'EOF'
@article{localkey,
  title = {Local},
}
EOF
    );

    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success when managed file is not listed');
    like($stdout, qr/not listed in the document's \\bibliography\{\.\.\.\} command/, 'missing managed bibliography is reported against the bibliography command');
    like($stdout, qr/Current bibliography setup appears to be \\bibliography\{adstex,custom\}\./, 'current bibliography command is shown');
    like($stdout, qr/Add paper\.adskeys to that command, or set \$managed_bib_file to match it/, 'fix direction is shown');
};


subtest 'canonicalized ADS lookups preserve the cited key in the managed bibliography' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{paper.adskeys}
\citation{2009LanB...4B...44L,2020NaMet..17..261V}
EOF
    );

    my @exported;
    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            no warnings 'redefine';
            local *ManagedBibliography::resolve_ads_bibcodes = sub {
                return (
                    'ok',
                    {
                        '2009LanB...4B...44L' => '2009LanB...4B..712L',
                        '2020NaMet..17..261V' => '2020NaMet..17..261V',
                    },
                    undef,
                );
            };
            local *ManagedBibliography::fetch_ads_bibtex_entries = sub {
                my ($keys_ref) = @_;
                push @exported, @{$keys_ref};
                return (
                    'ok',
                    <<'EOF'
@article{2009LanB...4B..712L,
  title = {Lodders},
}

@article{2020NaMet..17..261V,
  title = {SciPy},
}
EOF
                    ,
                    {},
                );
            };
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                        ads_api_token => 'token',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success after canonicalized lookup');
    is_deeply(
        [sort @exported],
        [qw(2009LanB...4B..712L 2020NaMet..17..261V)],
        'only canonical bibcodes are exported',
    );
    like($stdout, qr/ADS canonicalized <2009LanB\.\.\.4B\.\.\.44L> => <2009LanB\.\.\.4B\.\.712L>/, 'canonicalization is reported');
    like($stdout, qr/ADS returned entry for <2009LanB\.\.\.4B\.\.\.44L>/, 'alternate cited key is marked as resolved');
    like($stdout, qr/ADS returned entry for <2020NaMet\.\.17\.\.261V>/, 'canonical cited key is marked as resolved');
    is(
        read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib')),
        managed_bib_with_header(<<'EOF'),
@article{2009LanB...4B...44L,
  title = {Lodders},
}

@article{2020NaMet..17..261V,
  title = {SciPy},
}
EOF
        'managed bibliography preserves cited keys after canonicalized ADS lookup',
    );
};


subtest 'fetches only unresolved keys and appends returned entries' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{paper.adskeys,custom}
\citation{existingkey,localkey,newkey,missingkey}
EOF
    );

    write_file(
        File::Spec->catfile($tmpdir, 'paper.adskeys.bib'),
        <<'EOF'
@article{existingkey,
  title = {Existing},
}
EOF
    );

    write_file(
        File::Spec->catfile($tmpdir, 'custom.bib'),
        <<'EOF'
@article{localkey,
  title = {Local},
}
EOF
    );

    my @fetched;
    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            no warnings 'redefine';
            local *ManagedBibliography::resolve_ads_bibcodes = sub {
                my ($keys_ref) = @_;
                return (
                    'ok',
                    { map { $_ => $_ } @{$keys_ref} },
                    undef,
                );
            };
            local *ManagedBibliography::fetch_ads_bibtex_entries = sub {
                my ($keys_ref) = @_;
                push @fetched, @{$keys_ref};
                return (
                    'ok',
                    <<'EOF'
@article{newkey,
  title = {Fetched},
}
EOF
                    ,
                    {
                        newkey => 1,
                    },
                );
            };
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                        ads_api_token => 'token',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success with stubbed ADS export');
    is_deeply(
        [sort @fetched],
        [qw(missingkey newkey)],
        'only unresolved keys are sent to ADS',
    );
    like($stdout, qr/ADS returned entry for <newkey>/, 'fetch success is reported');
    like($stdout, qr/ADS returned no entry for <missingkey>/, 'fetch miss is reported');

    my $managed_bib = read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib'));
    like($managed_bib, qr/^% Managed bibliography file generated by managed-bibliography\.pl\./, 'managed bibliography header is written');
    like($managed_bib, qr/\@article\{existingkey,/, 'existing managed entry remains');
    like($managed_bib, qr/\@article\{newkey,/, 'fetched entry is appended');
    ok(!-e File::Spec->catfile($tmpdir, 'paper.keys.tex'), 'no citation key cache file is created after fetch');
};


subtest 'managed bibliography is rewritten sorted by key' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{paper.adskeys}
\citation{akey,mkey,zkey}
EOF
    );

    write_file(
        File::Spec->catfile($tmpdir, 'paper.adskeys.bib'),
        <<'EOF'
@article{zkey,
  title = {Existing},
}
EOF
    );

    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            no warnings 'redefine';
            local *ManagedBibliography::resolve_ads_bibcodes = sub {
                my ($keys_ref) = @_;
                return (
                    'ok',
                    { map { $_ => $_ } @{$keys_ref} },
                    undef,
                );
            };
            local *ManagedBibliography::fetch_ads_bibtex_entries = sub {
                return (
                    'ok',
                    <<'EOF'
@article{mkey,
  title = {Middle},
}

@article{akey,
  title = {First},
}
EOF
                    ,
                    {
                        akey => 1,
                        mkey => 1,
                    },
                );
            };
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                        ads_api_token => 'token',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success for sorted rewrite');
    like($stdout, qr/Writing 3 ADS entries to paper\.adskeys\.bib/, 'write message reports the number of managed entries');
    is(
        read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib')),
        managed_bib_with_header(<<'EOF'),
@article{akey,
  title = {First},
}

@article{mkey,
  title = {Middle},
}

@article{zkey,
  title = {Existing},
}
EOF
        'managed bibliography is sorted by citation key',
    );
};


subtest 'rewrite preserves ADS-style escaped entries and replaces updated keys' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);
    my $managed_bib_path = File::Spec->catfile($tmpdir, 'paper.adskeys.bib');

    write_file(
        $managed_bib_path,
        managed_bib_with_header(<<'EOF'),
@ARTICLE{1958ZA.....46..108B,
  author = {{B{\"o}hm-Vitense}, E.},
  title = "{{\"U}ber die Wasserstoffkonvektionszone}",
}

@ARTICLE{2002Sci...295...82K,
  title = {Original},
}
EOF
    );

    capture_stdout(
        sub {
            ManagedBibliography::append_bibliography_entries(
                $managed_bib_path,
                <<'EOF'
@ARTICLE{2002Sci...295...82K,
  title = {Replacement},
}
EOF
            );
        }
    );

    is(
        read_file($managed_bib_path),
        managed_bib_with_header(<<'EOF'),
@ARTICLE{1958ZA.....46..108B,
  author = {{B{\"o}hm-Vitense}, E.},
  title = "{{\"U}ber die Wasserstoffkonvektionszone}",
}

@ARTICLE{2002Sci...295...82K,
  title = {Replacement},
}
EOF
        'rewrite keeps ADS-style escaped entries and replaces by key without duplicates',
    );
};


subtest 'missing token leaves existing managed bibliography unchanged' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);
    my $managed_bib = managed_bib_with_header(<<'EOF');
@article{existingkey,
  title = {Existing},
}
EOF

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{paper.adskeys}
\citation{existingkey,missingkey}
EOF
    );

    write_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib'), $managed_bib);

    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success without token on populated managed file');
    like($stdout, qr/ADS API token unavailable/, 'missing token is reported for populated managed file');
    is(
        read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib')),
        $managed_bib,
        'managed bibliography is unchanged when token is missing',
    );
};


subtest 'authentication failure is reported clearly and stops ADS retries' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{paper.adskeys,custom}
\citation{authkey,otherkey}
EOF
    );

    write_file(
        File::Spec->catfile($tmpdir, 'custom.bib'),
        <<'EOF'
@article{localkey,
  title = {Local},
}
EOF
    );

    my @fetched;
    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            no warnings 'redefine';
            local *ManagedBibliography::resolve_ads_bibcodes = sub {
                my ($keys_ref) = @_;
                return (
                    'ok',
                    { map { $_ => $_ } @{$keys_ref} },
                    undef,
                );
            };
            local *ManagedBibliography::fetch_ads_bibtex_entries = sub {
                my ($keys_ref) = @_;
                push @fetched, @{$keys_ref};
                return ('auth', undef, 401);
            };
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                        ads_api_token => 'bad-token',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success on auth failure');
    is_deeply(\@fetched, [qw(authkey otherkey)], 'bulk auth failure happens in one ADS attempt for all unresolved keys');
    like($stdout, qr/ADS authentication failed \(HTTP 401\)/, 'auth failure is reported clearly');
    unlike($stdout, qr/ADS lookup failed for <authkey>/, 'generic per-key failure message is not used for auth');
    is(
        read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib')),
        managed_bib_with_header(''),
        'managed bibliography keeps only its header on auth failure',
    );
};


subtest 'authentication failure leaves existing managed bibliography unchanged' => sub {
    my $tmpdir = tempdir(CLEANUP => 1);
    my $managed_bib = managed_bib_with_header(<<'EOF');
@article{existingkey,
  title = {Existing},
}
EOF

    write_file(
        File::Spec->catfile($tmpdir, 'paper.aux'),
        <<'EOF'
\relax
\bibdata{paper.adskeys}
\citation{existingkey,authkey}
EOF
    );

    write_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib'), $managed_bib);

    my ($rc, $stdout) = run_in_dir(
        $tmpdir,
        sub {
            no warnings 'redefine';
            local *ManagedBibliography::resolve_ads_bibcodes = sub {
                my ($keys_ref) = @_;
                return (
                    'ok',
                    { map { $_ => $_ } @{$keys_ref} },
                    undef,
                );
            };
            local *ManagedBibliography::fetch_ads_bibtex_entries = sub {
                return ('auth', undef, 401);
            };
            return capture_stdout(
                sub {
                    ManagedBibliography::manage_bibliography(
                        document_base => 'paper',
                        ads_api_token => 'bad-token',
                    );
                }
            );
        }
    );

    is($rc, 0, 'manage_bibliography returns success on auth failure with populated managed file');
    like($stdout, qr/ADS authentication failed \(HTTP 401\)/, 'auth failure is reported for populated managed file');
    is(
        read_file(File::Spec->catfile($tmpdir, 'paper.adskeys.bib')),
        $managed_bib,
        'managed bibliography is unchanged on auth failure',
    );
};

done_testing;
